### ISSUE TITLE
Wrong Variable Format on Fresh Compass Project

### ISSUE THREAD

**Issue by greenz** [nextmat/compass-960-plugin#24] opened 2011-05-12 16:12 UTC
I just started using compass and noticed the following issue when building a project. 

I issued the following command after creating a new rails project {Doesn't give me the prompt to answer any questions!}

compass init rails . --syntax sass --using 960

All my directories get setup and everything compiles fine. I see no errors but when i go into grid.sass the following line gives an error when viewing a default template.

!ninesixty-columns = 16

Now i maybe a newbie but changing the variable to the following works fine. 

$ninesixty-columns: 16

I just thought that once setup it should work out of the box fine with no changes to the variables.

Thanks and I really appreciate the plugin it allows beginning developers a chance to start off on the right root. 
Oh and if possible can you implement support for 960.gs right out of the box just like blueprint.

**Comment by nextmat** [comment] 2011-05-12 17:53
Yep, that looks like a hold-over from the old syntax that needs to be fixed. 

Which version of the compass-960 gem are you using? Is it the latest, 0.10.3?

The blueprint support is maintained as part of the main Compass project, if you wanted to see this in the main project it would be best to raise the issue there.

**Comment by greenz** [comment] 2011-05-13 22:14
I am using 10.03 the latest version.

**Comment by greenz** [comment] 2011-05-15 02:51
Thanks Nextmat. I would also like to suggest a type of beginner's tutorial for this plugin something along the lines of 

http://compass-style.org/examples/compass/layout/sticky-footer/

While being new to the CSS framework and using a Grid System such as 960.gs i have been searching around and really haven't seen an all in one tutorial that includes the following. 

a) show you a basic layout:  header {maybe include navi bar} content{2/3 columns couple of different shaded boxes} : footer
b) give exact haml and sass source code

I just think its helps a beginner to visualize the placement of certain items along with the haml and sass code to go with it. I would be more than willing to offer my time and any help. I say this because using this framework along with the plugin has helped me visualize the placement of my divs on the webpage. If you throw this in along with the html 5 boilerplate plugin can come with a a truly DRY sematic website in under 10 minutes that even a beginner can do.

**Comment by nextmat** [comment] 2011-05-19 03:42
That is very cool, I think that's a great idea. @chriseppstein, any plans to allow plugin docs through the main site or a specific venue for plugin docs to allow this kind of thing?

**Comment by nextmat** [comment] 2011-05-19 03:51
greenz, I'm having trouble replicating your issue. The ninesixty-columns variable is generated as $ninesixty-columns with either syntax. can you try to reproduce the problem, post your versions of sass and compass and include the whole grid.sass file that you are seeing generated?

Thanks.

**Comment by chriseppstein** [comment] 2011-05-19 07:12
@nextmat we definitely need a documentation tool for sass

**Comment by nextmat** [comment] 2011-05-28 06:22
Closing this issue as I can't reproduce, @greenz if you can replicate, please post your version per my previous comment. Thanks!

**Closed as completed by nextmat** 2011-05-28 06:22 UTC
